.gitignore

- Edit .gitignore
- 이 PR을 볼 팀원에게 전달할 메세지를 작성해주세요

conf : edit .gitignore

---

build.gradle
src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/config/WebConfig.java
src/main/java/com/finalproject/recruit/controller/AuthController.java
src/main/resources/application.properties

- 프로젝트 기초 frame 구성 및 Redis & CORS 설정값 추가
* 프로젝트 기반폴더(controller, service 등) 추가
* CORS 설정값 추가
* 'org.springframework.boot:spring-boot-starter-security' build.gradle 추가
* config/SecurityConfig.java 추가
* config/WebSecurity.java 추가
* Redis 설정값 수정
*  build.gradle 수정 ( start => starter )
* 다중 properties 파일 사용에 따른 application.properties 인자값 추가
* Redis 관련 패키지 빌드가 잘 되는지 확인 부탁드려요!

request: Merge Develop branch

---

.github/workflows/main.yml

conf: main.yml 수정

---

build.gradle
src/main/java/com/finalproject/recruit/config/RedisConfig.java
src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/dto/UserResDTO.java
src/main/java/com/finalproject/recruit/jwt/JwtAuthenticationFilter.java
src/main/java/com/finalproject/recruit/jwt/JwtTokenProvider.java

- Security 및 JWT 토큰 설정 추가
- 작성한 부분까지만 올려둡니다.
- 이상한 부분, 이해가 안 가는 부분은 말씀해주시면 같이 찾아보면서 이해하면 좋을 것 같아요
- 안되는 부분은 바로 공유 부탁드립니다.

Conf : Security 및 JWT 토큰 설정 추가

---

src/main/java/com/finalproject/recruit/entity/Recruit.java
src/main/java/com/finalproject/recruit/entity/apply/Activities.java
src/main/java/com/finalproject/recruit/entity/apply/Awards.java
src/main/java/com/finalproject/recruit/entity/apply/Career.java
src/main/java/com/finalproject/recruit/entity/apply/Certificate.java
src/main/java/com/finalproject/recruit/entity/apply/Education.java
src/main/java/com/finalproject/recruit/entity/apply/Military.java

Refactor : Entity 필드타입 변경 - #15

---

src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/entity/Recruit.java

Refactor : Column 매핑 수정 - #15

---

src/main/java/com/finalproject/recruit/controller/MemberController.java
src/main/java/com/finalproject/recruit/dto/member/MemberReqDTO.java
src/main/java/com/finalproject/recruit/repository/MemberRepository.java
src/main/java/com/finalproject/recruit/service/MemberService.java

- 회원 정보 변경 API 작성
- Query method의 경우 확인 후 수정 필요

feat : 회원 정보 변경 API 구현 - #21

---

src/main/java/com/finalproject/recruit/controller/MemberController.java
src/main/java/com/finalproject/recruit/repository/MemberRepository.java
src/main/java/com/finalproject/recruit/service/MemberService.java

- 회원 탈퇴 API 작성
- Query method의 경우 확인 후 수정 필요

feat : 회원 탈퇴 API 구현 - #36

---

src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/entity/apply/Language.java
src/main/java/com/finalproject/recruit/parameter/EduYear.java
src/main/java/com/finalproject/recruit/parameter/LanguageLevel.java

- Entity 설계
- Entity 내용 수정하였습니다

Refactor : Entity 수정 - #15

---

src/main/java/com/finalproject/recruit/dto/member/MemberReqDTO.java
src/main/java/com/finalproject/recruit/dto/member/MemberResDTO.java
src/main/java/com/finalproject/recruit/entity/Member.java
src/main/java/com/finalproject/recruit/jwt/JwtTokenProvider.java
src/main/java/com/finalproject/recruit/repository/MemberRepository.java
src/main/java/com/finalproject/recruit/service/MemberService.java

Refactor : Refactor Auth part method & token

---

src/main/java/com/finalproject/recruit/controller/MemberController.java

- Controller Refactoring
- 
- 누락부분 추가 업데이트 합니다

Refactor : Controller Refactoring - #50

---

src/main/java/com/finalproject/recruit/controller/RecruitController.java
src/main/java/com/finalproject/recruit/exception/recruit/ErrorCode.java
src/main/java/com/finalproject/recruit/exception/recruit/RecruitException.java
src/main/java/com/finalproject/recruit/service/RecruitService.java

- 채용폼 관련기능 추가
- 검색 / 상세조회 / 수정 / 신규등록 / 삭제 기능추가
- 각 기능구현에 필요한 controller & service 메소드 추가
- 인증부분은 제외하고 기능구현 진행
- Postman을 통한 테스트 결과, 모두 정상작동 확인
- 신규등록시 생성되는 채용지원 url 예시 : https://www.jobkok.com/view/{recruit_id}
- 도메인값 확정 시, 수정예정
- 확인 후 문의사항이 있을경우 코멘트 부탁드립니다~!

feat: 채용폼 관련기능 추가

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/dto/applymanage/ApplyResponseDTO.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재관리 서비스의 조회 관련 기능 개발하였습니다. 
- 전체 지원자 조회 개발
- 단계별 지원자 조회 개발
이슈 별로 풀리퀘 차례대로 올리겠습니다!!
페이지네이션 관련은 이슈 모두 처리 후 리팩에서 진행하겠습니다!

feat: 인재관리 서비스의 조회 관련 기능 개발 (전체지원자 조회, 단계별 지원자 조회) - #67

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재관리 서비스 - 채용단계 변경 , 합격/불합격 처리 기능
- 지원자 채용단계 변경 기능 개발
- 지원자 합격 / 불합격 처리 기능 개발
리뷰 부탁드리겠습니다

feat: 인재관리 서비스 채용단계 변경 및 합격/불합격 처리 기능 구현 - #68

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/dto/applymanage/CountAndDateResponseDTO.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재관리 서비스의 인재현황 기능 개발
- 총 지원자 수 개발
- 오늘 지원자 수 개발
- 현재 채용폼의 채용단계 개발
- 채용단계 마감까지 D-day 개발

feat: 인재관리 서비스의 인재현황 관련 기능 개발 - #69

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
src/main/java/com/finalproject/recruit/dto/applymanage/CertificateResponseDTO.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/entity/apply/Activities.java
src/main/java/com/finalproject/recruit/entity/apply/Awards.java
src/main/java/com/finalproject/recruit/entity/apply/Career.java
src/main/java/com/finalproject/recruit/entity/apply/Certificate.java
src/main/java/com/finalproject/recruit/entity/apply/Education.java
src/main/java/com/finalproject/recruit/entity/apply/Language.java
src/main/java/com/finalproject/recruit/entity/apply/Military.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재 상세페이지 서비스의 지원자 상세 조회 기능 개발
- 지원자 상세 조회 개발

feat: 인재 상세페이지 서비스의 지원자 상세 조회 기능 개발 - #70

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재 상세페이지 서비스 다수 개발
- 지원자 코멘트 등록
- 지원자 찜 등록 / 해제
- 지원자 탈락보관함 등록 / 해제

feat: 인재 상세페이지 서비스 개발 (지원자 코멘트 등록, 찜하기, 탈락인재 보관함 이동) - #71,#72

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재 상세페이지 서비스 (지원자 서류검토 처리, 면접일자 지정)
- 지원자 서류검토 처리 (검토 버튼 클릭시 날짜 입력)
- 지원자 면접일자 지정 (파라미터로 들어오는 날짜 등록)

feat: 인재 상세페이지 서비스 (지원자 서류검토 처리, 면접일자 지정) - #73

---

src/main/java/com/finalproject/recruit/controller/ApplicantController.java
src/main/java/com/finalproject/recruit/controller/KeepController.java
src/main/java/com/finalproject/recruit/controller/NoticeController.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/NoticeService.java

feat: 지원자 검색 api - #81

---

src/main/java/com/finalproject/recruit/controller/KeepController.java
src/main/java/com/finalproject/recruit/controller/NoticeController.java
src/main/java/com/finalproject/recruit/dto/applicant/ApplicationReq.java
src/main/java/com/finalproject/recruit/dto/keep/ApplicantsRes.java
src/main/java/com/finalproject/recruit/dto/notice/NoticeRecruitsRes.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplicantService.java
src/main/java/com/finalproject/recruit/service/KeepService.java
src/main/java/com/finalproject/recruit/service/NoticeService.java

- 탈락인재, 알림인재, 삭제인재 페이지네이션
- 지원자 
- 확인 부탁드립니다~ 키워드 받는 방법 일단은 "keyword1,keyword2"이런식입니다

feat: 페이지네이션 및 지원자 로직 변경 - #88

---

src/main/java/com/finalproject/recruit/controller/MemberController.java
src/main/java/com/finalproject/recruit/service/MemberService.java

- Parameter Change
- 기존 Parameter로 RequestHeader를 사용하여 토큰 값을 받아오던 부분을 변경했습니다

Refactor : Parameter changed - #13

---

src/main/java/com/finalproject/recruit/exception/applicant/ApplicantException.java
src/main/java/com/finalproject/recruit/exception/applicant/ErrorCode.java
src/main/java/com/finalproject/recruit/exception/authorization/ErrorCode.java
src/main/java/com/finalproject/recruit/exception/keep/ErrorCode.java
src/main/java/com/finalproject/recruit/exception/keep/KeepException.java
src/main/java/com/finalproject/recruit/exception/recruit/ErrorCode.java
src/main/java/com/finalproject/recruit/service/ApplicantService.java
src/main/java/com/finalproject/recruit/service/KeepService.java
src/main/java/com/finalproject/recruit/service/MemberService.java
src/main/java/com/finalproject/recruit/service/NoticeService.java
src/main/java/com/finalproject/recruit/service/RecruitService.java

- 채용폼/지원서/인재보관/알림 예외처리 스타일링
* Exception 관련 return 스타일링 설정
* try문 내 exception 발생 => response.fail 타입반환
* catch를 통한 exception 발생 => throw new {Recruit/Applicant/Keep/..}Exception 타입반환
* Recruit/Applicant/Keep/Notice 예외처리 스타일링 적용
* 이를 위해 각각 전용Exception 및 ErrorCode 생성
- 요청이 서버에서 제대로 수행되지 않는경우, front-end 로 전달되는 response body를 통일시켰습니다!
- front에서 예외처리에 대한 return 값 문의시 확인 부탁드립니다!

refact: Styling Exception

---

src/main/java/com/finalproject/recruit/config/RedisConfig.java
src/main/java/com/finalproject/recruit/entity/Member.java
src/main/java/com/finalproject/recruit/exception/member/ErrorCode.java
src/main/java/com/finalproject/recruit/exception/member/MemberException.java
src/main/java/com/finalproject/recruit/jwt/JwtManager.java
src/main/java/com/finalproject/recruit/service/MemberService.java
src/main/java/com/finalproject/recruit/service/TokenService.java

- 'Member' 파트 예외처리 추가 
* Redis Config & JwtManager 일부코드 스타일링 관련수정 : 로직변경 없음
* MemberService 전용 Exception & ErrorCode 생성
* 예외처리를 위해 Service 코드내, 대다수 기능 메소드별 분리 진행
* EX) Redis & 메일전송 부분 모두 별도의 메소드 구성
* response.success & ressponsse.fail return 내용추가
- 빌드 및 기본기능 테스트 시 정상작동 확인하였습니다
- 단, 세부테스트는 시간관계상 진행하지 못하였으니 확인 부탁드립니다!

feat: Add 'Member' Exception

---

src/main/java/com/finalproject/recruit/exception/applyManage/ApplyManageException.java
src/main/java/com/finalproject/recruit/exception/applyManage/ErrorCode.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java
src/main/java/com/finalproject/recruit/service/MemberService.java

- '지원자 관리' 일부 예외처리 기능추가
* ApplyManage 전용 Exception & ErrorCode 생성
* '지원자 전체 조회' 메소드 예외처리 적용
* 일부 핵심기능 메소드로 추출진행
- 확인 부탁드립니다!

feat: Add 'ApplyManage' Exception

---

src/main/java/com/finalproject/recruit/exception/authorization/ErrorCode.java
src/main/java/com/finalproject/recruit/jwt/JwtFilter.java
src/main/java/com/finalproject/recruit/jwt/JwtManager.java

- 필터에 토큰 정보 유효 여부 판단
- 간단한 에러 코드 추가

feat : Add Error/Exception - #13

---

src/main/java/com/finalproject/recruit/controller/KeepController.java
src/main/java/com/finalproject/recruit/dto/keep/ApplicantsRes.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplicantService.java
src/main/java/com/finalproject/recruit/service/KeepService.java

- 탈락인재 지원자 검색 api
- rebase를 pr 올리고 난 후에 해버려서 커밋로그가 2개찍혔습니다 ㅠㅠ

feat: 탈락인재 지원자 검색 api 추가 - #107

---

src/main/java/com/finalproject/recruit/controller/RecruitController.java
src/main/java/com/finalproject/recruit/dto/recruit/RecruitReq.java
src/main/java/com/finalproject/recruit/dto/recruit/RecruitRes.java
src/main/java/com/finalproject/recruit/entity/Recruit.java
src/main/java/com/finalproject/recruit/repository/RecruitRepository.java
src/main/java/com/finalproject/recruit/service/RecruitService.java

- 채용폼 등록타입 추가에 따른 코드수정
- Recruit Entity에 채용타입 추가
- 이에따른 Repository/Service/Controller/DTO 수정
- 도메인 등록에 따른 지원서 URL return값 변경 ( www.jobkok.com => jobkok.shop )
- 빌드 및 Postman 테스트결과 이상없음
- 확인부탁드립니다

feat: 채용폼 등록타입 추가에 따른 코드수정

---

appspec.yml

hotfix : appspec.yml 수정 - overwrite

---

.github/workflows/main.yml

hotfix : main.yml 파일 수정

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java

- 이메일 인증 api 권한 허용
securityConfig 파일 수정됐습니다!

fix : SecurityConfig 수정 - 이메일 인증 권한 검사 허용

---

src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재관리 서비스 - 채용단계별 지원자 조회 로직 수정
- 프론트 측에서 단계별 조회에서도 받는 것이 좋을 것 같다는 의견이 있어서 기존 우대가점과 키워드 리스트를 반환하지 않았으나 반환하도록 변경
- 추가로 엔티티그래프를 활용하여 조회하는 것으로 변경
로직부분 혹시 문제될만한 것 있으면 말씀해주세요 !

refactor: 인재관리 서비스 - 채용단계별 지원자 조회 로직 수정

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/controller/RecruitController.java
src/main/java/com/finalproject/recruit/repository/MemberRepository.java
src/main/java/com/finalproject/recruit/repository/RecruitRepository.java
src/main/java/com/finalproject/recruit/service/RecruitService.java

- 채용폼 전체조회 시 인자값 수정 & SecurityConfig Refact
* RequestParam의 'Type' 제거
* 이에따른 Repository/Service/Controller 로직수정
* SecurityConfig에서 사용되지 않은 부분제거
* Default옵션으로 처리중이였던 CORS 처리에, 사전에 작성해놓았던 CORS configuration 주입
* CORS 테스트결과 정상조회 확인
- 확인 부탁드립니다!

refact: change RecruitSelectAll logic & SecurityConfig

---

src/main/java/com/finalproject/recruit/dto/member/MemberResDTO.java
src/main/java/com/finalproject/recruit/exception/member/ErrorCode.java
src/main/java/com/finalproject/recruit/jwt/JwtManager.java
src/main/java/com/finalproject/recruit/service/MemberService.java

- 로그인 시 리턴정보 추가 / 토큰 유효기간 연장 시, 검증로직 추가 / 비밀번호 변경 시 검증로직 변경
* 로그인 시 return되는 정보추가 : ( 기업명, 대표자명, 이메일, 사업자등록번호, 전화번호 )
* 토큰 유효기간 연장 시, refresToken 검증로직 추가
* Redis에 저장된 refresToken이 Valid한지 검증하는 로직추가
* 해당 로직을 위해 RefreshToken 생성로직(jwtManager) 수정
* 변경된 비밀번호 검증로직 변경
* 기존 로그인 시 비밀번호 검증메소드와 별개의 로직적용
* postman 테스트결과 정상작동 확인
- 확인 부탁드립니다!

refact: loginResDTO / TokenExpiredTimeExtend / resetPasswordValidation

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java

- 이메일 중복 검사는 security 확인이 필요 없을 것 같아 권한 허용함

fix : SecurityConfig 수정 - 이메일 중복검사 권한 허용

---

src/main/java/com/finalproject/recruit/service/NoticeService.java

fix : 지원자 검색 API 수정 

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/controller/MemberController.java

- FE 요청에 따른 수정사항 적용
- 확인 한 번씩 해주세요!

Refactor : 매핑 타입 및 URL 변경

---

src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java

인재 상세페이지 서비스 - 지원자 상세조회 리턴값 변경
- 우대사항 내용 추가 및 불필요한 내용 삭제
제대로 반영되었는지 확인부탁드립니당!

refactor: 지원자 상세조회 리턴값 변경

---

src/main/java/com/finalproject/recruit/service/RecruitService.java

- Change return url
- FE 요청사항에 대한 변경사항 적용

Refactor : Change return url

---

src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

- 인재 상세페이지 서비스 - 지원자 상세 조회 시 리턴 값 수정
- 타임라인 관련 내용 추가 및 키워드 리스트 추가
빠진 부분 있는지 확인 부탁드립니다 ! 테스트는 해봤습니다 !

refactor: 인재 상세페이지 서비스 - 지원자 상세 조회 시 리턴 값 수정

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java

- Security Config update
- 비밀번호 재설정 역시 로그인을 하지 않은 상태에서 작동하는 API라 public urls에 등록했습니다

Refactor : Update Security Config

---

src/main/java/com/finalproject/recruit/service/RecruitService.java

Refactor : FE요청에 따른 리턴값 변경

---

src/main/java/com/finalproject/recruit/config/SecurityConfig.java
src/main/java/com/finalproject/recruit/controller/MemberController.java
src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
src/main/java/com/finalproject/recruit/entity/Apply.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java
src/main/java/com/finalproject/recruit/service/NoticeService.java
src/main/java/com/finalproject/recruit/service/RecruitService.java

- FE 요청에 따른 2차 수정
- 확인 부탁 드려요~

Release : 2차 수정 사항 적용

---

src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
src/main/java/com/finalproject/recruit/dto/applymanage/ApplyResponseDTO.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재관리 서비스 - 채용단계별 디데이 리턴값 수정
인재 조회시 failApply 리턴하도록 수정
- "일" 단어 빠짐 -> 추가
- 인재 조회시 failApply 리턴하도록 수정
리턴값만 수정했습니다

refactor: 채용단계별 디데이 리턴값 수정

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/dto/applymanage/MeetingDateReq.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

면접일 지정 API 파라미터 RequestBody로 받는 것으로 수정
- 프론트측 요청으로 @Requestparam 으로 받던 내용 @RequestBody로 받도록 수정
확인부탁드리겠습니다 !

refactor: 면접일 지정 API 파라미터 RequestBody로 받는 것으로 수정

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/dto/applymanage/EvaluationReq.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

* 인재 코멘트 등록 - 파라미터 변경 RequestBody로 변경
인재 코멘트 등록 - 파라미터 변경 RequestBody로 변경
- 인재 코멘트 등록 RequestBody로 변경
확인 부탁드립니다 !

refactor: 인재 코멘트 등록 파라미터 수정

---

src/main/java/com/finalproject/recruit/dto/applicant/ApplicationReq.java
src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
src/main/java/com/finalproject/recruit/dto/applymanage/CertificateResponseDTO.java
src/main/java/com/finalproject/recruit/entity/Apply.java

Apply 엔티티 Military 컬럼 중복 내용 삭제
- Apply 엔티티 Military 컬럼 중복 내용 삭제

refactor: Apply 엔티티 Military 컬럼 중복 내용 삭제

---

src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
src/main/java/com/finalproject/recruit/dto/applymanage/ApplyProcedureReq.java
src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java

인재관리 서비스 - 지원자 채용단계 변경 API 수정
- 기존 변경감지 사용하여 하나씩만 처리하던 것을 따로 쿼리 사용하여 여러 지원자를 선택하여 일괄변경 가능하도록 변경하였습니다.
코드 리뷰 부탁드리겠습니다 !

refactor: 인재관리 서비스 - 지원자 채용단계 변경 API 수정

---

src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
src/main/java/com/finalproject/recruit/service/ApplyManageService.java
src/test/java/com/finalproject/recruit/service/ApplyManageServiceTest.java
src/test/java/com/finalproject/recruit/service/CalcKeywordTest.java

- 키워드 점수 계산 메서드 테스트 로직 추가
- 쿼리 속도 개선
- 확인 부탁드립니다!

test: 테스트 코드 추가
